----------- Crear temporal ----------
create table temporal(
	NOMBRE_CLIENTE varchar,
	CORREO_CLIENTE varchar,
	CLIENTE_ACTIVO varchar,
	FECHA_CREACION date,
	TIENDA_PREFERIDA varchar,
	DIRECCION_CLIENTE varchar,
	CODIGO_POSTAL_CLIENTE varchar,
	CIUDAD_CLIENTE varchar,
	PAIS_CLIENTE varchar,
	FECHA_RENTA timestamp,
	FECHA_RETORNO timestamp,
	MONTO_A_PAGAR float8,
	FECHA_PAGO timestamp,
	NOMBRE_EMPLEADO varchar,
	CORREO_EMPLEADO varchar,
	EMPLEADO_ACTIVO varchar,
	TIENDA_EMPLEADO varchar,
	USUARIO_EMPLEADO varchar,
	CONTRASENA_EMPLEADO varchar,
    DIRECCION_EMPLEADO varchar,
    CODIGO_POSTAL_EMPLEADO varchar,
    CIUDAD_EMPLEADO varchar,
    PAIS_EMPLEADO varchar,
    NOMBRE_TIENDA varchar,
    ENCARGADO_TIENDA varchar,
    DIRECCION_TIENDA varchar,
    CODIGO_POSTAL_TIENDA varchar,
    CIUDAD_TIENDA varchar,
    PAIS_TIENDA varchar,
    TIENDA_PELICULA varchar,
    NOMBRE_PELICULA varchar,
    DESCRIPCION_PELICULA varchar,
    ANO_LANZAMIENTO int4,
    DIAS_RENTA int4,
    COSTO_RENTA float8,
    DURACION int4,
    COSTO_POR_DANO float8,
    CLASIFICACION varchar,
    LENGUAJE_PELICULA varchar,
    CATEGORIA_PELICULA varchar,
    ACTOR_PELICULA varchar
);
----------- eliminar temporal ----------
drop table temporal;